Update patch set 1
Patch Set 1:

A few questions:

- do we need to fix this to python 3?
- if I run this on my systems (Ubuntu 16.04, 18.04), I get the following error:

  File "/home/opnfv_geokun/kuberef/.tox/molecule/lib/python2.7/site-packages/backports/functools_lru_cache.py", line 149, in wrapper
      result = user_function(*args, **kwds)
  File "/home/opnfv_geokun/kuberef/.tox/molecule/lib/python2.7/site-packages/molecule/driver/docker.py", line 222, in sanity_checks
    from ansible.module_utils.docker.common import HAS_DOCKER_PY
  ImportError: No module named docker.common

Patch-set: 1
Reviewer: Gerrit User 585 <585@bbac25d2-bf60-4904-9ba8-a72fc000d6c5>